# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    # - master
    # - releases/*
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

variables:
  global_variable: value    

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          for ($i = 0; $i -lt 10; $i++) {
            "System_JobName $env:System_JobName"
            "System_JobDisplayName $env:System_JobDisplayName"
            "Agent_JobName $env:Agent_JobName"
            "global_variable $env:global_variable"
            sleep 5
          }

  - job: WindowsPSCore
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |

            "System_JobName $env:System_JobName"
            "System_JobDisplayName $env:System_JobDisplayName"
            "Agent_JobName $env:Agent_JobName"
            "global_variable $env:global_variable"
            gci env:


  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
            "System_JobName $env:System_JobName"
            "System_JobDisplayName $env:System_JobDisplayName"
            "Agent_JobName $env:Agent_JobName"
            "global_variable $env:global_variable"
            gci env:

    - bash: echo $(System_JobName)
    - bash: echo $(System.JobName)
    - bash: echo $(global_variable)

  - job: macOS
    pool:
      vmImage: 'macOS-latest'

    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          for ($i = 0; $i -lt 10; $i++) {
            "System_JobName $env:System_JobName"
            "System_JobDisplayName $env:System_JobDisplayName"
            "Agent_JobName $env:Agent_JobName"
            sleep 5
          }
